version: '1.0.{build}'
branches:
  only:
    - master
  except:
    - gh-pages
configuration: Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
  - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
build_script:
  - dotnet --info
  - appveyor-retry dotnet restore -v Information
  - dotnet build "src\Kelas.App.API" -c %CONFIGURATION% --version-suffix %LABEL%
test_script:
  - dotnet test "test\Kelas.App.Core.Test"
cache:
  - '%USERPROFILE%\.nuget\packages'